export enum EventCalendarTypeEnum {
  SCHEDULING_COLLABORATIVE = 'SCHEDULING_COLLABORATIVE',
  INVITE_SIMPLE = 'INVITE_SIMPLE',
  INVITE_PERIODIC = 'INVITE_PERIODIC',
  SCHEDULING_AUTOMATIC = 'SCHEDULING_AUTOMATIC'
}
